# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  # =========================================================
  # 🗄️ Machine 1 : NFS Storage (avec disque additionnel 10 Go)
  # =========================================================
  config.vm.define "nfs-storage" do |node|
    node.vm.hostname = "nfs-storage"
    node.vm.network "private_network"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "nfs-storage"
      vb.cpus = 2
      vb.memory = "2048"

      disk_file = "./disk_nfs_storage.vdi"

      unless File.exist?(disk_file)
        vb.customize ['createhd', '--filename', disk_file, '--size', 10240]
      end

      vb.customize ['storageattach', :id,
                    '--storagectl', 'SATA Controller',
                    '--port', 1,
                    '--device', 0,
                    '--type', 'hdd',
                    '--medium', disk_file]
    end
  end

  # =========================================================
  # 🗄️ Machine 2 : DB Server
  # =========================================================
  config.vm.define "db-server" do |node|
    node.vm.hostname = "db-server"
    node.vm.network "private_network"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "db-server"
      vb.cpus = 2
      vb.memory = "2048"
    end
  end

  # =========================================================
  # ☸️ Cluster K3s
  # =========================================================
  nodes = {
    "k3s-manager"  => { :cpus => 4, :mem => 3072 },
    "k3s-worker-1" => { :cpus => 4, :mem => 3072 },
    "k3s-worker-2" => { :cpus => 4, :mem => 3072 }
  }

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network"

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.cpus = opts[:cpus]
        vb.memory = opts[:mem]
      end
    end
  end
end
