# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"

  # Définition des machines avec leurs rôles
  nodes = {
    "k3s-manager"  => { :cpus => 4, :mem => 3072 }, # 3 Go
    "k3s-worker-1" => { :cpus => 4, :mem => 3072 },
    "k3s-worker-2" => { :cpus => 4, :mem => 3072 }
  }

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name
      
      # Réseau en mode Pont sur l'interface physique eno1
      node.vm.network "public_network", bridge: "eno1"

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.cpus = opts[:cpus]
        vb.memory = opts[:mem]
      end
    end
  end
end
